### ISSUE TITLE
RE: Removal of Cloze Brackets

### ISSUE THREAD

**Issue by gitjamd** [Arthaey/anki-cloze-blanks#1]
Great add-on. However, the cloze brackets (normally present) make the blanks look funny. Do you know of a way to remove/disable the brackets entirely?

**Comment by Arthaey** [comment]
I briefly looked at [anki/template.py](https://github.com/dae/anki/blob/08829da01109b4916125a5b4a9efeae3ee90c4eb/anki/template/template.py#L209) and tried just removing the brackets from there. It didn't work as expected, but maybe if you try poking around there a bit more, you'll figure it out.

If you do, please report back!
