### ISSUE TITLE
error with close blanks

### ISSUE THREAD

**Issue by Katz131** [Arthaey/anki-cloze-blanks#12]
my emailÑ abk93@cornell.edu

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\islan\AppData\Roaming\Anki2\addons\Cloze_Blanks.py", line 45, in _keyPressEvent
    if self.keyHandler(evt):
  File "anki\hooks.py", line 61, in repl
  File "C:\Users\islan\AppData\Roaming\Anki2\addons\Visual Feedback.py", line 48, in _keyHandler
    key = str(evt.text())
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 0: ordinal not in range(128)

**Comment by Arthaey** [comment]
The last line of the error message makes it look like this is actually a problem with the [Visual Feedback add-on](https://ankiweb.net/shared/info/1749604199). [The bug has been reported already](https://github.com/glutanimate/anki-addons-misc/issues/24), but maybe it would help that developer to know that you are seeing the problem too.

Good luck!
