### ISSUE TITLE
wrong add-on on ankiweb ?

### ISSUE THREAD

**Issue by ijgnd** [Arthaey/anki-cloze-blanks#13]
This addon is on ankiweb as https://ankiweb.net/shared/info/546020849 

If I enter the number 546020849 into Anki 2.0.52 I get a file that is named Cloze_Blanks.py but the content is all wrong. In fact it's a different addon. These are the first lines of the file **Cloze_Blanks.py** that I just downloaded from AnkiWeb [1]:

    # -*- coding: utf-8 -*-
    # See github page to report issues or to contribute:
    # https://github.com/Arthaey/anki-custom-keyboard-shortcuts
    #
    # Also available for Anki at https://ankiweb.net/shared/info/1483821271

    from aqt.qt import QMainWindow
    from aqt.main import AnkiQt

    ################################################################################
    #
    # USER-MODIFABLE SETTINGS. CHANGE THINGS HERE TO THE SETTINGS YOU WANT.
    #
    ################################################################################

    # CUSTOMIZE THESE SHORTCUT KEYS.
    GLOBAL_DECKS_SHORTCUT    = "d"

----
[1] I don't have the addon anki-custom-keyboard-shortcuts. So I'm pretty sure I made no mistake.

**Comment by ijgnd** [comment]
I forgot: Thanks for sharing your great add-ons. 

I have downloaded the code I need from github so this issue is not relevant for me personally.

**Comment by Arthaey** [comment]
How strange! I've uploaded the file again, so it should be the right one now.

Thank you for letting me know!
