### ISSUE TITLE
不起作用

### ISSUE THREAD

**Issue by wangcb80** [Arthaey/anki-cloze-blanks#14]
笔记类型：Cloze
应用时，提示为：Updated 0 cards(from 1 cloze notes) and replaced spaces inside clozes with non-breaking spaces.

**Comment by Arthaey** [comment]
Do you have any notes with clozes created yet?

If you don't have any cloze notes yet, this addon can't make any changes to them.

**Comment by wangcb80** [comment]
Please upload some notes and let me import and test them

**Comment by Arthaey** [comment]
This add-on is not a note template type of add-on. It intentionally does not add any new card types or notes to your Anki; **it only modifies your existing cards.**

It works with the default Cloze card type, so here's how you would use it:

1. Tools > **Manage Note Types**
2. Check that you have a "Cloze" type
   - if not, click "Add" and chose "**Add: Cloze**"
3. Close the "Manage Note Types" window
4. Click the **"Add" button** at the top of the deck list window (or from the card browser window)
5. **Set note type to "Cloze"**
6. **Fill in the "Text" field** with something that has at least one cloze in it.
   - for example: `This is a {{c1::cloze card}}.`
7. Click the **"Add" button** to save the new card.
8. Now run Tools > **Add blanks to cloze notes**

If you look at your new card now, you'll see that it's become something like `This is a {{c1::cloze card::___ __}}.`

Hope that helps!
