### ISSUE TITLE
First letter without blanks.

### ISSUE THREAD

**Issue by gitjamd** [Arthaey/anki-cloze-blanks#2]
I like the idea behind your add-on; however, I'm looking to just add first letter of each cloze with no blanks. Ideas on how I can accomplish that with your code? Thanks.

**Comment by Arthaey** [comment]
Done! If you grab the updated version, all you have to do is edit it like so:
- enable `"includeFirstLetter" : True,` if you haven't already done so (currently [line 21](https://github.com/Arthaey/anki-cloze-blanks/blob/b02bc4bc5bff025b7e8d50df34f26eb778921981/ClozeBlanks.py#L21))
- change the blank character from underscore to nothing: `BLANK = ""` (currently [line 25](https://github.com/Arthaey/anki-cloze-blanks/blob/b02bc4bc5bff025b7e8d50df34f26eb778921981/ClozeBlanks.py#L25))

Restart Anki and it should be good to go! Let me know if you have any other problems or suggestions. :)

**Comment by gitjamd** [comment]
So, excited about this. Works great! Any way to force capital letters and/or have something like "[R c]" look like [RC] or just [R]? That would make for a really solid add-on. Thanks for the help!
