### ISSUE TITLE
Hacky fix?

### ISSUE THREAD

**Issue by gitjamd** [Arthaey/anki-cloze-blanks#3]
It's regarding my previous comment:

"So, excited about this. Works great! Any way to force capital letters and/or have something like "[R c]" look like [RC] or just [R]? That would make for a really solid add-on. Thanks for the help!"

I have zero coding experience, but after about 2-3 hours was able to 1) determine that python is mad confusing, 2) figure out what your code was actually doing, and 3) painstakingly alter it just enough to accomplish the above. I'll continue to use my hacky version until you get some time to look into it. Just thought I'd let you know.

**Comment by Arthaey** [comment]
Nice job hacking together something that meets your needs! That's absolutely the way many programmers start down the slippery slope to nerddom. ;)

**Comment by gitjamd** [comment]
I'm a medical student. The nerdiness is there! I have a few suggestions for your add-on though.

**Comment by Arthaey** [comment]
Please do continue giving feedback & suggestions! My one request would be that you create a new issue for each one.

**Comment by gitjamd** [comment]
I added a few suggestions; there's also what I mentioned above. My hack sucks.
