### ISSUE TITLE
generate one cloze instead of several

### ISSUE THREAD

**Issue by evilisforever** [Arthaey/anki-cloze-blanks#8]
Hi. Would it be possible to add an option to generate something like this instead of multiple cloze deletions (one card out of many words)?

{{c1::Those::T__}} {{c1::who::w_}} {{c1::can::c_}} {{c1::make::m__}} {{c1::you::y_}} {{c1::believe::b___}} {{c1::absurdities::a_____}} {{c1::can::c_}} {{c1::make::m__}} {{c1::you::y_}} {{c1::commit::c___}} {{c1::atrocities.::a_____}} {{c1::Voltaire::V____}}

**Comment by Arthaey** [comment]
Find [line 126 of ClozeBlanks.py](https://github.com/Arthaey/anki-cloze-blanks/blob/master/ClozeBlanks.py#L126), where it says:

```
return u"{{{{c{0}::{1}::{2}}}}}".format(num, text, blanks)
```

Change it to this:

```
return u"{{{{c{0}::{1}::{2}}}}}".format("1", text, blanks)
```

Restart Anki and it should make all clozes the same cloze number.
