### ISSUE TITLE
Suggestion: Highlight mode (trivial clozes)

### ISSUE THREAD

**Issue by sbseltzer** [Arthaey/anki-cloze-blanks#9]
I've been looking for a portable way of doing what [cloze to highlight](https://ankiweb.net/shared/info/1224266113) does. Your addon's behaviour is very similar, but appears to works at the card content level as opposed to desktop display level.

In essence, I'm looking for a mode that trivially clozes cards.

`{{c1::my text}}` => `{{c1::my text::my text}}`

That gives me the freedom to play with how clozes display in javascript by myself. So far I haven't seen an addon that enables this.

I realize that sorta departs from the concept of "blanks", but it seems like this addon is functionally about automating hint text.

**Comment by sbseltzer** [comment]
Managed to get something working in my fork, though I think I might have broken some existing functionality (which is weird because my changes were mostly additive). Let me know if you'd be interested in merging. My use-case is pretty specialized so it's not too much of an issue for me. I'd never worked with Python so I wouldn't trust me to make sane changes. :P

**Comment by Arthaey** [comment]
If you ever got your changes working with normal cloze cards too, I'd be interested in accepting a pull request. Feel free to re-open this issue or just sent a PR if you want to! :)
